# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
    push:
        branches: ["master"]
jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven

            - run: |
                  mkdir -p src/main/resources/
                  touch src/main/resources/application.properties
                  echo "${{ secrets.MY_ENV }}" >> src/main/resources/application.properties

            - name: Build with Maven
              run: mvn -B package --file pom.xml

            # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
            # - name: Execute jar file
            #   run: sudo kill -9 `sudo lsof -t -i:8083` & sudo java -jar /home/ubuntu/actions-runner/_work/vncafe_be_spring/vncafe_be_spring/target/vncafe_be_spring-0.0.1-SNAPSHOT.jar & # tắt cổng
            - name: Execute jar file
              run: |
                  if lsof -t -i:8083 > /dev/null
                  then
                      sudo kill -9 `sudo lsof -t -i:8083`
                  fi
                  sudo java -jar /home/ubuntu/actions-runner/_work/vncafe_be_spring/vncafe_be_spring/target/vncafe_be_spring-0.0.1-SNAPSHOT.jar &
